# This is a reusable workflow that allows you to deploy the app to the environment using GitOps.
name: "Deploy"

# Define the event that triggers the workflow.
# This workflow is triggered by a workflow call event.
on:
  workflow_call:
    inputs:
      env:
        description: "Environment to be deployed."
        type: string
        required: true
      app:
        description: "Application to be deployed."
        type: string
        required: true
      gitops-repo:
        description: "GitOps repository used for deployment."
        type: string
        required: true

# Define the jobs that run in the workflow.
jobs:
  gitops-deploy:
    name: "With GitOps"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      # Step 1: Debug
      - name: Debug Info
        run: |
          echo "Deploying application ${{ inputs.app }} to environment ${{ inputs.env }} using GitOps repo ${{ inputs.gitops-repo }}"
        
      