# This is a reusable workflow that allows you to deploy the app to the environment using GitOps.
name: "Deploy"

# Define the event that triggers the workflow.
# This workflow is triggered by a workflow call event.
on:
  workflow_call:
    inputs:
      env:
        description: "Environment to be deployed."
        type: string
        required: true
      repository:
        description: "ECR Repository name."
        type: string
        required: true
      service:
        description: "Service to deploy."
        type: string
        required: true
      timeout-minutes:
        description: "Timeout in minutes for the ECS deployment."
        default: 10
        type: number

# Define the jobs that run in the workflow.
jobs:
  ecs-fargate:
    name: "ECS Fargate"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    steps:
      # Step 1: Checkout repo
      - name: Checkout Code
        run: |
          echo "Hi there!"
        
      